# Remove the version line entirely and update to modern syntax
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=urlshortener
      - DB_PASSWORD=securepassword
      - DB_NAME=urlshortener
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redispassword
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - urlshortener-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    networks:
      - urlshortener-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispassword --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - urlshortener-network
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  urlshortener-network: